name: ku_lost_found
description: "KU Lost & Found - A Flutter application for managing lost and found items at Kasetsart University."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_ui_auth: ^3.0.1
  firebase_ui_oauth_google: ^2.0.1
  firebase_auth: ^6.1.4
  camera: ^0.12.0
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Line Seed Sans TH
      fonts:
        - asset: assets/fonts/Line_Seed_Sans/LineSeedSansTH_He.ttf
        - asset: assets/fonts/Line_Seed_Sans/LineSeedSansTH_Rg.ttf
        - asset: assets/fonts/Line_Seed_Sans/LineSeedSansTH_Th.ttf
        - asset: assets/fonts/Line_Seed_Sans/LineSeedSansTH_XBd.ttf
        - asset: assets/fonts/Line_Seed_Sans/LineSeedSansTH.ttf
