// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4DpW6G-2qUU3DHGJBQmXceqVUfiOHtA',
    appId: '1:519948196017:web:c98e8bfc695c0ebc72aa90',
    messagingSenderId: '519948196017',
    projectId: 'ku-lost-and-found',
    authDomain: 'ku-lost-and-found.firebaseapp.com',
    storageBucket: 'ku-lost-and-found.firebasestorage.app',
    measurementId: 'G-ECBL9JRG35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrN7aAokrmvYJeIFgm-O1MRq39MYGaRk',
    appId: '1:519948196017:android:88fc53f6126bf6da72aa90',
    messagingSenderId: '519948196017',
    projectId: 'ku-lost-and-found',
    storageBucket: 'ku-lost-and-found.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOp7FRLDDIYMEcCzNol26QER9giD8eCH4',
    appId: '1:519948196017:ios:e30117ccc528ba7572aa90',
    messagingSenderId: '519948196017',
    projectId: 'ku-lost-and-found',
    storageBucket: 'ku-lost-and-found.firebasestorage.app',
    iosClientId: '519948196017-bdn63ejvnhufmmguv9km3p0hnepol5hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostNFoundTest',
  );

}